'use client';

import React from 'react';
import { Card } from '../ui/card';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  LineChart,
  Line,
} from 'recharts';

interface AnalyticsProps {
  routeRidership: Array<{
    name: string;
    studentsCount: number;
    receiptsCount: number;
    totalRevenue: number;
  }>;
}

export const AdminAnalyticsCharts: React.FC<AnalyticsProps> = ({ routeRidership }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
      {/* Chart 1: Ridership distribution by route */}
      <Card className="p-6">
        <h3 className="text-base font-bold text-slate-900 dark:text-white mb-4">
          Route Ridership Distribution (Students Count)
        </h3>
        <div className="h-72 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={routeRidership} margin={{ top: 10, right: 30, left: 0, bottom: 20 }}>
              <CartesianGrid strokeDasharray="3 3" opacity={0.2} />
              <XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} angle={-15} textAnchor="end" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="studentsCount" fill="#0EA5E9" radius={[8, 8, 0, 0]} name="Assigned Students" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </Card>

      {/* Chart 2: Revenue Generated by Route */}
      <Card className="p-6">
        <h3 className="text-base font-bold text-slate-900 dark:text-white mb-4">
          Revenue Breakdown by Route (PKR)
        </h3>
        <div className="h-72 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={routeRidership} margin={{ top: 10, right: 30, left: 0, bottom: 20 }}>
              <CartesianGrid strokeDasharray="3 3" opacity={0.2} />
              <XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} angle={-15} textAnchor="end" />
              <YAxis />
              <Tooltip formatter={(val: any) => `PKR ${val.toLocaleString()}`} />
              <Bar dataKey="totalRevenue" fill="#10B981" radius={[8, 8, 0, 0]} name="Total Revenue (PKR)" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </Card>
    </div>
  );
};
