export const ROLES = {
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
} as const;

export const RECEIPT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const BUS_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DELAYED: 'DELAYED',
} as const;

export const NOTIFICATION_TYPES = {
  FEE_REMINDER: 'FEE_REMINDER',
  RECEIPT_APPROVED: 'RECEIPT_APPROVED',
  RECEIPT_REJECTED: 'RECEIPT_REJECTED',
  BUS_DELAY: 'BUS_DELAY',
  HOLIDAY: 'HOLIDAY',
  GENERAL: 'GENERAL',
  EMERGENCY: 'EMERGENCY',
} as const;

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
};
